[tool.pytest.ini_options]
# 说明：迁移自 pytest.ini，集中到 pyproject.toml 以保持根目录简洁
# 测试收集路径
testpaths = ["tests"]

# 警告过滤，精确屏蔽第三方弃用警告，保留项目内告警
filterwarnings = [
  "ignore::DeprecationWarning:werkzeug.routing.rules",
  "ignore::DeprecationWarning:flask.scaffold",
  "ignore::DeprecationWarning:sqlalchemy.*",
  "ignore::DeprecationWarning:ast",
  "ignore::PendingDeprecationWarning",
]
