"""drop material.status column

Revision ID: 362aca3e4678
Revises: 
Create Date: 2025-08-22 10:00:16.507458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362aca3e4678'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
